name: Lint Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python v3.12.1
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.1'
  
    - name: Install poetry
      # uses: knowsuchagency/poetry-install@v1
      uses: snok/install-poetry@v1
      with: 
        virtualenvs-in-project: true

    - name: Poetry Install
      uses: knowsuchagency/poetry-install@v2
        
    - name: Load cached venv
      uses: actions/cache@v4
      id: cached-poetry-dependencies
      with: 
        path: .venv
        key: venv-${{runner.os}}-${{hashFiles('**/poetry.lock')}}
    

    # run: |
      #   curl -sSL https://install.python-poetry.org | python3 -
      #   export PATH="$HOME/.local/bin:$PATH"
    
      
    - name: Install dependencies using poetry
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry run make install

    - name: Lint with flake8
      run: poetry run make check
      