name: Lint Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python v3.12.1
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.1'
  
    - name: Install poetry
      uses: knowsuchagency/poetry-install@v1
    
    # run: |
      #   curl -sSL https://install.python-poetry.org | python3 -
      #   export PATH="$HOME/.local/bin:$PATH"
    
    - name: Install dependencies using poetry
      run: poetry install

    - name: Lint with flake8
      run: poetry run make check